name: Bug Report
description: Report a bug or issue with the template
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: dropdown
    id: category
    attributes:
      label: Bug Category
      description: What type of bug is this?
      options:
        - Tool Functionality
        - Data Validation
        - Performance
        - Security
        - Documentation
        - Configuration
        - CI/CD Workflows
        - Dependencies
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Clone the template...
        2. Run command '...'
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe expected behavior...
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe actual behavior...
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g., macOS 14.0]
        - Node.js version: [e.g., 22.0.0]
        - Package manager: [e.g., npm 10.0.0]
        - Template version: [e.g., 1.0.0]
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Any relevant error messages or logs
      placeholder: Paste logs here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context...
    validations:
      required: false
